name: job-posting-nlp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas=0.25.3
  - numpy=1.17.5
  - scikit-learn=0.22.1
  - matplotlib=3.1.2
  - plotly=4.5.0
  - cufflinks-py=0.17.0
  - pip=20.0.1
  - jupyter_core=4.6.1
  - wordcloud=1.6.0
  - beautifulsoup4=4.8.2
  - lxml=4.4.2
